### PR TITLE
Add KillSwitch to runIntoableProcess and bump libraries

### PR DESCRIPTION
**Pull request by aquamatthias**

### CODE REVIEW

**Comment by hseeberger** [comment]
What is the motivation to use kill an intoable process? 
Please understand that killing an intoable process can lead to requests (already accepted by the upstream processor) being lost.

**Comment by aquamatthias** [comment]
Yes. The kill switch is only used during shutdown to ensure a clean tear down behaviour.

**Comment by hseeberger** [comment]
I see. Please make sure to register killing in a phase *after* killing front processors to make sure no more requests are in flight.

**Comment by aquamatthias** [comment]
Thanks @hseeberger - happy to see you active here!

**Pull request merged**
