### PR TITLE
Replaced BroadcastHub with Sink.queue 

### PR DESCRIPTION
**Pull request by haghard**
Replaced BroadcastHub with Sink.queue as many to one is good enough for this use case

### CODE REVIEW

**Comment by hseeberger** [comment]
Thanks for you contribution. I have some questions (but for the typos I have already created https://github.com/moia-dev/streamee/pull/80).

First, could you please explain the motivation for switching from BroadcastHub to Sink.queue.

Second, other than BroadcastHub, calling pull on Sink.queue might fail. How do you deal with that?

**Comment by haghard** [comment]
My initial idea was that `MergeHub.source` combined with `BroadcastHub.sink` models many to many shape (like a chat room where one writes and all participators receive). Looks like this in not what we need in this particular case. As far as I understand the `errors` sink materialises  just once which tells me that in runtime it always has many to one shape and this shape can/should be represented as  a combination of  `MergeHub.source` and `Sink.queue`. Correct me if I'm wrong.

**Comment by haghard** [comment]
Yes, you are right `pull` on `Sink.queue` might fail but it only fails if the whole stream fails. I think this change doesn't break anything and stays semantically equal to original version with `BroadcastHub.sink`

**Comment by hseeberger** [comment]
Well, a BroadcastHub could be materialized many times and then we would have something like a n-m-shape (with n, m > 1), but in our case we only materialize it once. Anyway, what's the problem with this, or what benefits come from using a Sink.queue. Are there any runtime (memory or speed) benefits? Code-wise I do not see a big difference, we could switch or not.

Please don't get me wrong, this is very interesting and I am learning a lot.

**Comment by haghard** [comment]
Sure, technically there is no problem and I assume, expect same performance. For me it was like as soon as I noticed a `MergeHub.source` connected with a `BroadcastHub.sink` I started to think about multiple outputs. But the use cases I found clearly assume just one output channel, and it was confusing to me. In the end it is just to make the intention clear.

**Comment by hseeberger** [comment]
Thanks for the explanation. Well, as this is a very implementation detail, I do not think "making the intention clear" justifies this change – in particular, because I do not think that a broadcast hub with a single materialization is unclear. 

What I like about the current implementation is the symmetry by MergeHub and BroadcastHub, which is also not a good reason ;-)

If you find compelling arguments, e.g. performance, I'd happily merge.

**Pull request closed without merging**
